name: Stage 1 Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-stage1:
    if: contains(github.event.head_commit.message, 'stage-1')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Stage 1 tests
        run: npm run test:stage1
